#include <string.h>

#include "lwip/apps/fs.h"

static const char INDEX_HTML[] =
  "<!doctype html><html><head><meta charset='utf-8'><title>Pico BrowserIO</title>"
  "<meta name='viewport' content='width=device-width,initial-scale=1'>"
  "<style>"
  ":root{--bg:#0b0f14;--bg2:#111827;--fg:#e6edf3;--dim:#9ca3af;--line:#334155;--ok:#22c55e;--err:#ef4444;}"
  "body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.4 monospace;}"
  ".bar{padding:8px;border-bottom:1px solid #1f2937;background:var(--bg2);display:flex;gap:8px;align-items:center;flex-wrap:wrap}"
  "label{display:flex;gap:6px;align-items:center}"
  "input,select,button{background:#0f172a;color:var(--fg);border:1px solid var(--line);padding:4px 8px}"
  "#shell{display:grid;grid-template-columns:1fr;gap:0;height:calc(100vh - 102px)}"
  "#shell.hex{grid-template-columns:2fr 1fr}"
  "#shell.vt #term{display:none}"
  "#shell.vt #termvt{display:block}"
  ".pane{min-height:0;overflow:auto;padding:10px;white-space:pre-wrap;word-break:break-word;border-right:1px solid #1f2937;outline:none}"
  "#term{color:var(--fg)}"
  "#termvt{display:none;padding:0;white-space:normal;word-break:normal}"
  "#hex{color:#93c5fd;background:#0a1222;display:none}"
  "#shell.hex #hex{display:block}"
  ".ok{color:var(--ok)}.err{color:var(--err)}.dim{color:var(--dim)}"
  ".ansi-bold{font-weight:bold}"
  ".fg30{color:#111}.fg31{color:#ef4444}.fg32{color:#22c55e}.fg33{color:#eab308}.fg34{color:#3b82f6}.fg35{color:#a855f7}.fg36{color:#06b6d4}.fg37{color:#e5e7eb}"
  ".fg90{color:#6b7280}.fg91{color:#f87171}.fg92{color:#4ade80}.fg93{color:#facc15}.fg94{color:#60a5fa}.fg95{color:#c084fc}.fg96{color:#22d3ee}.fg97{color:#f9fafb}"
  ".bg40{background:#111}.bg41{background:#7f1d1d}.bg42{background:#14532d}.bg43{background:#713f12}.bg44{background:#1e3a8a}.bg45{background:#581c87}.bg46{background:#164e63}.bg47{background:#d1d5db}"
  ".bg100{background:#374151}.bg101{background:#991b1b}.bg102{background:#166534}.bg103{background:#854d0e}.bg104{background:#1d4ed8}.bg105{background:#7e22ce}.bg106{background:#0e7490}.bg107{background:#f3f4f6}"
  "#tx{width:min(460px,95vw)}"
  ".pending{outline:2px solid #f59e0b;background:#3b2a0a}"
  "#dirty{display:none;color:#f59e0b;font-weight:bold}"
  "#dirty.show{display:inline}"
  ".cursor{display:inline-block;width:8px;height:1em;background:#e6edf3;vertical-align:bottom;animation:blink 1s steps(1,end) infinite}"
  "@keyframes blink{50%{opacity:0}}"
  "</style>"
  "</head><body>"
  "<div class='bar'>"
  "<label>Baud <input id='baud' type='number' value='115200' min='300' step='100'></label>"
  "<label>Data <select id='data'><option>8</option><option>7</option></select></label>"
  "<label>Parity <select id='parity'><option value='none'>none</option><option value='even'>even</option><option value='odd'>odd</option></select></label>"
  "<label>Stop <select id='stop'><option value='1'>1</option><option value='2'>2</option></select></label>"
  "<label>Enter <select id='enter'><option value='cr'>\\r</option><option value='lf'>\\n</option><option value='crlf'>\\r\\n</option></select></label>"
  "<label>Send <select id='sendmode'><option value='type'>as you type</option><option value='line'>on Enter only</option></select></label>"
  "<label>Decode <select id='decode'><option value='plain'>plain</option><option value='ansi'>ansi colors</option><option value='vt100'>vt100 (xterm.js)</option></select></label>"
  "<label><input id='hexview' type='checkbox'>hex view</label>"
  "<label>Hex cols <input id='hexcols' type='number' value='16' min='4' max='64' step='1'></label>"
  "<label>Hex gap ms <input id='hexgap' type='number' value='100' min='10' max='2000' step='10'></label>"
  "<label><input id='localecho' type='checkbox'>local echo</label>"
  "<button id='apply'>Apply</button>"
  "<span id='dirty'>settings changed - press Apply</span>"
  "<span id='st'>connecting...</span>"
  "</div>"
  "<div class='bar'>"
  "<input id='tx' type='text' placeholder='Send byte sequence (e.g. 01 02 ff or 0x41,0x42)'>"
  "<button id='sendbytes'>Send Bytes</button>"
  "<button id='clear'>Clear Terminal Output</button>"
  "<span class='dim'>Tip: click terminal pane to type</span>"
  "</div>"
  "<div id='shell'><div id='term' class='pane' tabindex='0'></div><div id='termvt' class='pane'></div><div id='hex' class='pane'></div></div>"
  "<script>"
  "const term=document.getElementById('term');"
  "const termVt=document.getElementById('termvt');"
  "const hex=document.getElementById('hex');"
  "const shell=document.getElementById('shell');"
  "const st=document.getElementById('st');"
  "const applyBtn=document.getElementById('apply');"
  "const dirty=document.getElementById('dirty');"
  "const sendMode=document.getElementById('sendmode');"
  "const enterMode=document.getElementById('enter');"
  "const decodeMode=document.getElementById('decode');"
  "const hexView=document.getElementById('hexview');"
  "const hexCols=document.getElementById('hexcols');"
  "const hexGap=document.getElementById('hexgap');"
  "const localEcho=document.getElementById('localecho');"
  "const tx=document.getElementById('tx');"
  "const cursor=document.createElement('span');cursor.className='cursor';"
  "const ws=new WebSocket('ws://'+location.hostname+':81/ws');"
  "ws.binaryType='arraybuffer';"
  "const enc=new TextEncoder();"
  "const dec=new TextDecoder('utf-8',{fatal:false});"
  "let lineBuf='';"
  "let hexOffset=0;"
  "let pendingHex=[];"
  "let hexTimer=null;"
  "let xterm=null;"
  "let xtermLoading=false;"
  "let xtermFailed=false;"
  "const sgr={bold:false,fg:'',bg:''};"
  "function markDirty(v){if(v){applyBtn.classList.add('pending');dirty.classList.add('show');}else{applyBtn.classList.remove('pending');dirty.classList.remove('show');}}"
  "function keepCursor(){if(cursor.parentNode)cursor.parentNode.removeChild(cursor);term.appendChild(cursor);}"
  "function atBottom(el){return el.scrollHeight-el.scrollTop-el.clientHeight<8;}"
  "function appendTerm(text,cls){const stick=atBottom(term);const span=document.createElement('span');if(cls)span.className=cls;span.textContent=text;term.appendChild(span);keepCursor();if(stick)term.scrollTop=term.scrollHeight;}"
  "function appendTermStyled(text){const cls=[sgr.bold?'ansi-bold':'',sgr.fg,sgr.bg].filter(Boolean).join(' ');appendTerm(text,cls);}"
  "function parseSgr(code){if(!code||code==='0'){sgr.bold=false;sgr.fg='';sgr.bg='';return;}code.split(';').forEach(c=>{const n=parseInt(c||'0',10);if(n===0){sgr.bold=false;sgr.fg='';sgr.bg='';}"
  "else if(n===1)sgr.bold=true;else if(n===22)sgr.bold=false;else if(n===39)sgr.fg='';else if(n===49)sgr.bg='';"
  "else if((n>=30&&n<=37)||(n>=90&&n<=97))sgr.fg='fg'+n;else if((n>=40&&n<=47)||(n>=100&&n<=107))sgr.bg='bg'+n;});}"
  "function appendAnsi(text){let i=0;while(i<text.length){const esc=text.indexOf('\\u001b[',i);if(esc<0){appendTermStyled(text.slice(i));break;}if(esc>i)appendTermStyled(text.slice(i,esc));const m=/^\\u001b\\[([0-9;]*)m/.exec(text.slice(esc));if(!m){appendTermStyled(text.slice(esc,esc+1));i=esc+1;continue;}parseSgr(m[1]);i=esc+m[0].length;}}"
  "function appendHexNow(bytes){if(!hexView.checked)return;const stick=atBottom(hex);let out='';const cols=Math.max(4,Math.min(64,parseInt(hexCols.value,10)||16));for(let i=0;i<bytes.length;i+=cols){const chunk=bytes.slice(i,i+cols);"
  "const off=(hexOffset+i).toString(16).padStart(8,'0');"
  "const hx=Array.from(chunk,b=>b.toString(16).padStart(2,'0')).join(' ');"
  "const asc=Array.from(chunk,b=>(b>=32&&b<=126)?String.fromCharCode(b):'.').join('');"
  "out+=off+'  '+hx.padEnd(cols*3-1,' ')+'  '+asc+'\\n';}"
  "hexOffset+=bytes.length;hex.textContent+=out;if(stick)hex.scrollTop=hex.scrollHeight;}"
  "function flushHex(){if(!pendingHex.length)return;const b=Uint8Array.from(pendingHex);pendingHex=[];appendHexNow(b);}"
  "function queueHex(bytes){if(!hexView.checked)return;for(const v of bytes)pendingHex.push(v);if(hexTimer)clearTimeout(hexTimer);"
  "const gap=Math.max(10,Math.min(2000,parseInt(hexGap.value,10)||100));hexTimer=setTimeout(()=>{hexTimer=null;flushHex();},gap);}"
  "function enterBytes(){if(enterMode.value==='lf')return new Uint8Array([10]);if(enterMode.value==='crlf')return new Uint8Array([13,10]);return new Uint8Array([13]);}"
  "function sendBinary(arr){if(ws.readyState===1)ws.send(arr);}"
  "function sendTextLine(str){if(!str)return;sendBinary(enc.encode(str));}"
  "function parseByteInput(s){const toks=s.trim().split(/[\\s,]+/).filter(Boolean);const out=[];for(const t0 of toks){let t=t0.toLowerCase();if(t.startsWith('0x'))t=t.slice(2);"
  "if(!/^[0-9a-f]{1,2}$/.test(t))throw new Error('bad byte: '+t0);out.push(parseInt(t,16));}return new Uint8Array(out);}"
  "function send(o){if(ws.readyState===1)ws.send(JSON.stringify(o));}"
  "function loadScript(src){return new Promise((ok,fail)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=fail;document.head.appendChild(s);});}"
  "function loadCss(href){if(document.querySelector('link[data-xterm]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.setAttribute('data-xterm','1');document.head.appendChild(l);}"
  "async function ensureXterm(){if(xterm||xtermLoading||xtermFailed)return;xtermLoading=true;try{loadCss('https://unpkg.com/xterm@5.3.0/css/xterm.css');"
  "if(!window.Terminal){try{await loadScript('https://unpkg.com/xterm@5.3.0/lib/xterm.js');}catch(_){await loadScript('https://unpkg.com/xterm/lib/xterm.js');}}"
  "xterm=new window.Terminal({cursorBlink:true,convertEol:false,theme:{background:'#0b0f14',foreground:'#e6edf3'}});xterm.open(termVt);xterm.onData(d=>sendBinary(enc.encode(d)));xterm.write('\\r\\n[VT100 mode active]\\r\\n');}"
  "catch(_){xtermFailed=true;appendTerm('\\n[error failed to load xterm.js, check internet access]\\n','err');decodeMode.value='ansi';shell.classList.remove('vt');}finally{xtermLoading=false;}}"
  "function syncDecodeMode(){if(decodeMode.value==='vt100'){shell.classList.add('vt');ensureXterm();}else{shell.classList.remove('vt');}}"
  "ws.onopen=()=>{st.textContent='connected';st.className='ok';send({type:'hello'});send({type:'uart.get_config',port:'uart0'});term.focus();};"
  "ws.onclose=()=>{st.textContent='disconnected';st.className='err';};"
  "ws.onmessage=(e)=>{"
  " if(typeof e.data==='string'){"
  "  try{const m=JSON.parse(e.data);"
  "   if(m.type==='uart.config'){appendTerm('\\n[config '+JSON.stringify(m)+']\\n','ok');}"
  "   else if(m.type==='error'){appendTerm('\\n[error '+(m.msg||'unknown')+']\\n','err');}"
  "   else{appendTerm('\\n['+e.data+']\\n');}"
  "  }catch(_){appendTerm(e.data);}"
  " }else{const b=new Uint8Array(e.data);queueHex(b);const txt=dec.decode(b);if(decodeMode.value==='vt100'&&xterm){xterm.write(txt);}else if(decodeMode.value==='ansi')appendAnsi(txt);else appendTerm(txt);}"
  "};"
  "applyBtn.onclick=()=>{"
  " send({type:'uart.set_config',port:'uart0',baud:parseInt(document.getElementById('baud').value,10)||115200,"
  " data_bits:parseInt(document.getElementById('data').value,10)||8,parity:document.getElementById('parity').value,"
  " stop_bits:parseInt(document.getElementById('stop').value,10)||1,flow:'none'});"
  " markDirty(false);"
  "};"
  "document.getElementById('sendbytes').onclick=()=>{try{const b=parseByteInput(tx.value);if(!b.length)return;sendBinary(b);}catch(err){appendTerm('\\n[error '+err.message+']\\n','err');}};"
  "document.getElementById('clear').onclick=()=>{term.textContent='';hex.textContent='';hexOffset=0;lineBuf='';pendingHex=[];if(hexTimer){clearTimeout(hexTimer);hexTimer=null;}if(xterm)xterm.clear();sgr.bold=false;sgr.fg='';sgr.bg='';keepCursor();};"
  "['baud','data','parity','stop'].forEach(id=>{const el=document.getElementById(id);el.addEventListener('input',()=>markDirty(true));el.addEventListener('change',()=>markDirty(true));});"
  "hexCols.addEventListener('input',()=>{hexOffset=0;hex.textContent='';});"
  "decodeMode.addEventListener('change',syncDecodeMode);"
  "hexView.onchange=()=>{if(hexView.checked){shell.classList.add('hex');}else{shell.classList.remove('hex');pendingHex=[];if(hexTimer){clearTimeout(hexTimer);hexTimer=null;}}};"
  "term.addEventListener('keydown',(e)=>{"
  " if(decodeMode.value==='vt100')return;"
  " if(ws.readyState!==1)return;"
  " if(sendMode.value==='type'){"
  "  if(e.key==='Enter'){sendBinary(enterBytes());if(localEcho.checked)appendTerm('\\n','dim');}"
  "  else if(e.key==='Backspace'){sendBinary(new Uint8Array([127]));if(localEcho.checked)appendTerm('\\b','dim');}"
  "  else if(e.key.length===1){sendBinary(enc.encode(e.key));if(localEcho.checked)appendTerm(e.key,'dim');}"
  "  else return;"
  " }else{"
  "  if(e.key==='Enter'){sendTextLine(lineBuf);sendBinary(enterBytes());if(localEcho.checked)appendTerm('\\n','dim');lineBuf='';}"
  "  else if(e.key==='Backspace'){if(lineBuf.length>0)lineBuf=lineBuf.slice(0,-1);}"
  "  else if(e.key.length===1){lineBuf+=e.key;if(localEcho.checked)appendTerm(e.key,'dim');}"
  "  else return;"
  " }"
  " e.preventDefault();"
  "});"
  "syncDecodeMode();"
  "keepCursor();"
  "</script></body></html>";

int fs_open_custom(struct fs_file *file, const char *name) {
  if (!file || !name) return 0;

  if (strcmp(name, "/") == 0 || strcmp(name, "/index.html") == 0) {
    file->data = INDEX_HTML;
    file->len = (int)strlen(INDEX_HTML);
    file->index = file->len;
    file->flags = 0;
#if LWIP_HTTPD_FILE_EXTENSION
    file->pextension = NULL;
#endif
#if HTTPD_PRECALCULATED_CHECKSUM
    file->chksum = NULL;
    file->chksum_count = 0;
#endif
#if LWIP_HTTPD_FILE_STATE
    file->state = NULL;
#endif
    return 1;
  }

  return 0;
}

void fs_close_custom(struct fs_file *file) {
  LWIP_UNUSED_ARG(file);
}
